# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/optimize_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_conf = QtWidgets.QWidget()
        self.tab_conf.setObjectName("tab_conf")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_conf)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab_conf, "")
        self.tab_contour = QtWidgets.QWidget()
        self.tab_contour.setObjectName("tab_contour")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_contour)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_contour = QtWidgets.QVBoxLayout()
        self.verticalLayout_contour.setObjectName("verticalLayout_contour")
        self.verticalLayout_2.addLayout(self.verticalLayout_contour)
        self.tabWidget.addTab(self.tab_contour, "")
        self.tab_3d = QtWidgets.QWidget()
        self.tab_3d.setObjectName("tab_3d")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3d)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3d = QtWidgets.QVBoxLayout()
        self.verticalLayout_3d.setObjectName("verticalLayout_3d")
        self.verticalLayout_3.addLayout(self.verticalLayout_3d)
        self.tabWidget.addTab(self.tab_3d, "")
        self.tab_metrics = QtWidgets.QWidget()
        self.tab_metrics.setObjectName("tab_metrics")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_metrics)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_metrics = QtWidgets.QVBoxLayout()
        self.verticalLayout_metrics.setObjectName("verticalLayout_metrics")
        self.verticalLayout_6.addLayout(self.verticalLayout_metrics)
        self.tabWidget.addTab(self.tab_metrics, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Оптимизация"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conf), _translate("MainWindow", "Конфигурация"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_contour), _translate("MainWindow", "Контур"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3d), _translate("MainWindow", "3D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_metrics), _translate("MainWindow", "Метрики"))
